= Analysis of Comparing Short Text using Cosine Similarity (word2vec gensim) and Jaccard Similarity

== Problem Description

Suppose  we have short text say for example tweets and want to do comparison between the tweets
to find the similarity. There are different similarity measures which could be used to find
similarity. For example : Cosine, Jaccard . This exercise is to apply , understand and compare

1. doc2vec and cosine similarity
2. Jaccard Similarity

For doc2vec Gensim is used and similarity is calculated using cosine. Jaccard and cosine are implemented.

The goal is to know whether to use doc2vec with cosine or Jaccard.

== Data & Experiment


* Data
----
docs1 = ["This is a sentence", "This is another sentence"]
docs2 = ["11 CRPF personnel killed in naxal attack at Chattisgarh","11 CRPF personnel killed in encounter with Naxal in Chhattisgarh Sukma"]
----

As you can see docs1 has two sentences and docs2 has two sentences.

* Execute the code1
- In the main class, use the following code

----
doc1_list = docs2[0].lower().split(" ")
doc2_list = docs2[1].lower().split(" ")
g = textcompare()
g.rungensim(docs2)
g.jaccard(doc1_list,doc2_list)
----
- Execute the code
----
$python textcompare.py
----
* Result1
----
cosine sim  -0.224094
jaccard 0.46153846153846156
----

* Execute the code2
- In the main class, use the following code

----
doc1_list = docs1[0].lower().split(" ")
doc2_list = docs1[1].lower().split(" ")

g = textcompare()
g.rungensim(docs1)
g.jaccard(doc1_list,doc2_list)
----
- Execute the code
----
$python textcompare.py
----

* Result2
----
cosine sim  -0.825705
jaccard 0.6
----


== Analysis

After running the above sample code with two different data points, it may be noticed that there is negative number for cosine.
However, for different run of the same code the similarity value changes and it is positive and higher as well. This is due to the window size of the vector.
The Gensim way i.e word2vec is more suitable for large text. Gensim creates vectors with a fixed length is useful for larger text.
For smaller text it is advisable to use something like Jaccard.
Though cosine could have been used directly without the Gensim, however creating a vector and doing a comparison would have been an additional overhead.


== Observation

* It may be observed that removal of stopwords or cleaning of data is not done.
* However, the exercise here was to understand the purpose of some algorithms and know when to use what.
* Note, here we are not trying to do semantic similarity as well.
* Cosine is generally used for larger text like news articles or reports, however the length of the text compared should be equal to get the accurate results.
* Also, in terms of performance the jaccard is performing better with a very minute difference of 2ms.
